#development:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: hi_development
#  pool: 5
#  username: paarth
#  password: paarth
#  socket: /var/run/mysqld/mysqld.sock
development:
  adapter: postgresql
  encoding: unicode
  database: fb_analytics_dev
  username: postgres
  password: password
